name: Docker Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push events
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Docker Container
        run: docker build . --tag ghcr.io/jass-2021/fake-tello
      - name: Login to GitHub Container registry

        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/trunk'

      - name: Push Docker Container
        run: docker push ghcr.io/jass-2021/fake-tello:latest
        if: github.ref == 'refs/heads/trunk'

